---

# TODO: Remove these in favor of simpler `pm2 startup`.
# PM2 startup tasks via 
# https://github.com/weareinteractive/ansible-pm2/blob/master/tasks/install.yml
- name: Looking up user home
  shell: >
    egrep "^{{ pm2_user }}:" /etc/passwd | awk -F: '{ print $6 }'
  changed_when: false
  register: pm2_user_home

- name: Installing startup script
  command: "pm2 startup systemd -u {{ pm2_user }} --hp {{ pm2_user_home.stdout }}"
  become: true

- name: Save APP
  command: pm2 save 
