---

- name: Initial configuration for a {{ application_name }} server
  hosts: all
  become: yes
  become_user: root
  remote_user: web4u4less
  vars:
    - update_apt_cache: yes
  vars_files:
    - roles/base/defaults/main.yml

  roles:
    - security
