---

- name: Create the application user
  user: name={{ pm2_user }} state=present

#already there
- name: Create the application group
  group: name={{ pm2_group }} system=yes state=present

- name: Add the application user to the application group
  user: name={{ pm2_user }} group={{ pm2_group }} state=present
